#version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY="w6$5!mb3veysj6u^l_bl$1zzug4f49^su8l5*j)v^*hu!5$sit"
      - DEBUG = 1
      - ALLOWED_HOSTS = "127.0.0.1"
    command: python manage.py runserver