# Generated by Django 3.1.7 on 2021-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=0)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'InActive')], max_length=1)),
            ],
        ),
    ]
